# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: step_download 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "step_download"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Julik Tarkhanov"]
  s.date = "2016-03-07"
  s.description = "Send bursts of large files quickly via Rack"
  s.email = "me@julik.nl"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "README.md",
    "Rakefile",
    "config.ru",
    "lib/fast_send.rb",
    "spec/fast_send_with_mocks_spec.rb",
    "spec/fast_send_with_puma_spec.rb",
    "spec/test_app.ru",
    "step_download.gemspec"
  ]
  s.homepage = "https://gitlab.wetransfer.net/julik/fast_send"
  s.licenses = ["Proprietary"]
  s.rubygems_version = "2.2.2"
  s.summary = "and do so bypassing the Ruby VM"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["> 2"])
      s.add_development_dependency(%q<rspec>, ["~> 3"])
      s.add_development_dependency(%q<puma>, [">= 0"])
      s.add_development_dependency(%q<sendfile>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["> 2"])
      s.add_dependency(%q<rspec>, ["~> 3"])
      s.add_dependency(%q<puma>, [">= 0"])
      s.add_dependency(%q<sendfile>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["> 2"])
    s.add_dependency(%q<rspec>, ["~> 3"])
    s.add_dependency(%q<puma>, [">= 0"])
    s.add_dependency(%q<sendfile>, [">= 0"])
  end
end

